version: '3.8'

services:
  fastapi-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: deepseek-fastapi
    ports:
      - "8000:8000"
    volumes:
      - ./:/app
    environment:
      OLLAMA_HOST: http://ollama:11434
    depends_on:
      - ollama

  ollama:
    build:
      context: .
      dockerfile: Dockerfile.ollama
    container_name: ollama-cpu
    ports:
      - "11434:11434"
    volumes:
      - ollama:/root/.ollama

volumes:
  ollama:
