version: '3.8'

services:
  fastapi-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: deepseek-fastapi
    ports:
      - "8000:8000"
    environment:
      OLLAMA_HOST: ${OLLAMA_HOST}
    depends_on:
      - ollama
    restart: unless-stopped

  ollama:
    build:
      context: .
      dockerfile: Dockerfile.ollama
    container_name: ollama-cpu
    ports:
      - "11434:11434"
    volumes:
      - ollama:/root/.ollama
    restart: unless-stopped

volumes:
  ollama:
